### ISSUE TITLE
Jellyfin repository

### ISSUE THREAD

**Issue by dannycool87** [jellyfin/jellycon#13]
Hello, why didn't you open this new branch in the Jellyfin directory?  Since everything is open source and available, it would only be easier and more visible to the whole community.

**Comment by mcarlton00** [comment]
Assuming you're asking why it's under `mcarlton00` instead of `github.com/jellyfin/`, it's just not there yet.  Typically what we've done in the past is if somebody forks a project, they hold it in their account until it's in a stable state and they're happy with it, and then if there's interest we move it into the org.  With the 10.6 release cycle and trying to work through some issues on Jellyfin for Kodi and Mopidy-Jellyfin, I just haven't been able to give this project as much love as I'd like yet.

If you're asking why it's not available in `https://repo.jellyfin.org/releases/client/kodi/`, then it's coming.  The repo has been going through an overhaul to be compatible with the breaking changes in kodi 19.  Knowing those changes were coming, there wasn't a big rush to get this addon added to the repo.

**Comment by mcarlton00** [comment]
Ths project has now been moved to the Jellyfin org.
