### ISSUE TITLE
Login to Jellyfin Server not possible (quick connect also not working with this addon)

### ISSUE THREAD

**Issue by MisterT87** [jellyfin/jellycon#359]
**Describe the bug**
Jellyfin detected my local Server with autodiscovery -> when I choose the auto entry I got and Addon error (Jellyfin Server expect Servername with http(s) prefix, but for now only hostname is saved when choosing entry from auto discovery).

Then anyway I changed the hostname to http://hostname in the Addon Settings.
Login was fine...

But could not use Quick connect and I have enabled it and already used it.
The Addon dont display the 6 digits code (Only can choose manual login).

So I used manual login:
Put in my username and password.
After Accepting it nothing happened (only last window closes, no errors).
Only see the normal Addon Menu (I think), but when I choose "Watch Libraries" -> there are no libraries.

Even My Jellyfin Server didnt recognized a login from a new devices...

**To Reproduce**
Just install / reinstall newest Addon version and follow assistant - then you can see the login / autodiscovery bugs.

**Expected behavior**
That I can login and can test my librarys ? :D

**System (please complete the following information):**
 - OS: LibreElec 12.0.1 (Linux based)
 - Jellyfin Version: 10.10.3
 - Kodi Version: 21.1
 - Addon Version: 0.8.0

**Additional context**
just for my info: Is this addon still maintained ?

**Comment by mcarlton00** [comment]
Yes, it's still maintained.  No, it hasn't seen much activity lately because it works for all of my use cases and I haven't had free time to add new features for other people.

Thank you for not including logs, which is the single most important detail you could have included.  That section is in the issue template for a reason.

Autodetection and quickconnect both work fine on my systems.  Without any more info, my guess is that your server is configured incorrectly.  When you set up the Server URI that's used for autodiscovery, you _need_ to include a scheme in the URL (http/https).  Sounds like yours doesn't have that, you tried to use autodiscovery, saved an invalid URL, and now it seems stuck that way somewhere.

Assuming this is what happened, you should clear the addon data and either fix your server, or skip the autodiscovery step and manually put in a URL.

**Comment by MisterT87** [comment]
nah sorry maybe its also a broken SD card - i have to fix first (I mean would be a reason why no logfiles was created) :D 

I only wanted to ask and doing a great job ! <3 
Dont get me wrong: thats not I wanted to achive with this

Give me some time to fix my sd card first, if I found real bugs I can reopen this issue again :)

Keep up your good work !
